### ISSUE TITLE
simulator cannot be used on Windows with python 3.11

### ISSUE THREAD

**Issue by Zhaoyilunnn** [ScQ-Cloud/pyquafu#174]
# System Info

OS: Windows 11
Python: 3.11.9
PyQuafu version: 0.4.0

# How to reproduce

run following script fails

```python
from quafu import QuantumCircuit, simulate

qc = QuantumCircuit(2)
qc.h(0)
qc.cnot(0, 1)

res = simulate(qc)
```

报错如下
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\quafu\simulators\__init__.py", line 41, in simulate
    from .simulator import SVSimulator
  File "C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\quafu\simulators\simulator.py", line 19, in <module>
    from .qfvm import simulate_circuit, applyop_statevec, expect_statevec, sampling_statevec,simulate_circuit_clifford
ImportError: DLL load failed while importing qfvm: 找不到指定的模块。
```

**Comment by Zhaoyilunnn** [comment]
## Debug Log

### 20240618
Successfully build from source on Windows 11 and `simulate` works well. Seems to be issue with CI environment.

**Comment by Zhaoyilunnn** [comment]
https://github.com/ScQ-Cloud/pyquafu/pull/176

The root cause is the debug flag
